workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

include:
  - local: '.gitlab/ci/base.yml'
  - local: '.gitlab/ci/verify.yml'
  - local: '.gitlab/ci/package.yml'
  - local: '.gitlab/ci/image.yml'
  - local: '.gitlab/ci/deploy-user-center.yml'
  - local: '.gitlab/ci/deploy-auth-center.yml'
  - local: '.gitlab/ci/deploy-bl-center.yml'
