spring:
  datasource:
    driver-class-name: ${BL_CENTER_DATASOURCE_DRIVER_CLASS_NAME:dm.jdbc.driver.DmDriver}
    url: ${BL_CENTER_DATASOURCE_URL:jdbc:dm://127.0.0.1:5236}
    username: ${BL_CENTER_DATASOURCE_USERNAME:SYSDBA}
    password: ${BL_CENTER_DATASOURCE_PASSWORD:Dm.2027.Pwd.}
  flyway:
    enabled: ${BL_CENTER_FLYWAY_ENABLED:false}
