spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blcenter;MODE=LEGACY;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  flyway:
    enabled: ${BL_CENTER_FLYWAY_ENABLED:true}
  h2:
    console:
      enabled: false
