-- 达梦完整部署基线 M3-M6 兼容补丁
-- 适用场景：已手工导入旧版 docs/database/达梦完整部署基线.sql 的库，无需清库即可补齐 M3-M6 依赖结构。

DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'TECHNICAL_SPECIMEN_REGISTRATIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE technical_specimen_registrations (
                case_id VARCHAR2(64) NOT NULL,
                application_id VARCHAR2(64) NOT NULL,
                registration_status VARCHAR2(32) NOT NULL,
                registered_by_user_id VARCHAR2(64),
                registered_by_name VARCHAR2(128),
                registered_at TIMESTAMP,
                remarks VARCHAR2(500),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL,
                CONSTRAINT pk_technical_specimen_registrations PRIMARY KEY (case_id),
                CONSTRAINT fk_technical_specimen_reg_case FOREIGN KEY (case_id) REFERENCES pathology_cases (id)
            )';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLINGS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE samplings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLINGS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE samplings ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLING_BLOCKS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE sampling_blocks ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SAMPLING_BLOCKS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE sampling_blocks ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCHES' AND COLUMN_NAME = 'CASE_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batches ADD COLUMN case_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCHES' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batches ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCHES' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batches ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCH_ITEMS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batch_items ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCH_ITEMS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batch_items ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMBEDDINGS' AND COLUMN_NAME = 'SAMPLING_BLOCK_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE embeddings ADD COLUMN sampling_block_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMBEDDINGS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE embeddings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMBEDDINGS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE embeddings ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMBEDDING_BOXES' AND COLUMN_NAME = 'SAMPLING_BLOCK_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE embedding_boxes ADD COLUMN sampling_block_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMBEDDING_BOXES' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE embedding_boxes ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLICINGS' AND COLUMN_NAME = 'EMBEDDING_BOX_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slicings ADD COLUMN embedding_box_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLICINGS' AND COLUMN_NAME = 'SLICE_COUNT_PER_SLIDE';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slicings ADD COLUMN slice_count_per_slide NUMBER(10)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLICINGS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slicings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLICINGS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slicings ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDES' AND COLUMN_NAME = 'EMBEDDING_BOX_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slides ADD COLUMN embedding_box_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDES' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slides ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDE_STAININGS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slide_stainings ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDE_STAININGS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slide_stainings ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REWORK_ORDERS' AND COLUMN_NAME = 'SAMPLING_BLOCK_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE rework_orders ADD COLUMN sampling_block_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REWORK_ORDERS' AND COLUMN_NAME = 'EMBEDDING_BOX_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE rework_orders ADD COLUMN embedding_box_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REWORK_ORDERS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE rework_orders ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REWORK_ORDERS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE rework_orders ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDE_QC_EVALUATIONS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slide_qc_evaluations ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SLIDE_QC_EVALUATIONS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slide_qc_evaluations ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CASE_MEDIA_ASSETS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE case_media_assets ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CASE_MEDIA_ASSETS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE case_media_assets ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DIAGNOSTIC_TASKS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE diagnostic_tasks ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PATHOLOGY_REPORTS' AND COLUMN_NAME = 'REMARKS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE pathology_reports ADD COLUMN remarks VARCHAR2(500)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PATHOLOGY_REPORTS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE pathology_reports ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PATHOLOGY_REPORTS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE pathology_reports ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REPORT_REVISION_REQUESTS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE report_revision_requests ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REPORT_REVISION_REQUESTS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE report_revision_requests ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'EXECUTOR_USER_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN executor_user_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'EXECUTOR_NAME';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN executor_name VARCHAR2(100)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'ACCEPTED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN accepted_at TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'COMPLETED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN completed_at TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'CANCELLED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN cancelled_at TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEDICAL_ORDERS' AND COLUMN_NAME = 'REMARKS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE medical_orders ADD COLUMN remarks VARCHAR2(500)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_CASES' AND COLUMN_NAME = 'HOST_USER_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_cases ADD COLUMN host_user_id VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_CASES' AND COLUMN_NAME = 'HOST_NAME';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_cases ADD COLUMN host_name VARCHAR2(100)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_CASES' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_cases ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_CASES' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_cases ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_PARTICIPANTS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_participants ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CONSULTATION_PARTICIPANTS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE consultation_participants ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_CABINETS' AND COLUMN_NAME = 'LAYER_COUNT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_cabinets ADD COLUMN layer_count NUMBER(10) DEFAULT 1 NOT NULL'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_CABINETS' AND COLUMN_NAME = 'SLOT_COUNT_PER_LAYER';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_cabinets ADD COLUMN slot_count_per_layer NUMBER(10) DEFAULT 1 NOT NULL'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_CABINETS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_cabinets ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_CABINETS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_cabinets ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_POSITIONS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_positions ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ARCHIVE_POSITIONS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE archive_positions ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SPECIMEN_STORAGE_RECORDS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE specimen_storage_records ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SPECIMEN_STORAGE_RECORDS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE specimen_storage_records ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MATERIAL_LOANS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE material_loans ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MATERIAL_LOANS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE material_loans ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BILLING_RECORDS' AND COLUMN_NAME = 'EXTERNAL_SYSTEM';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE billing_records ADD COLUMN external_system VARCHAR2(64)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BILLING_RECORDS' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE billing_records ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BILLING_RECORDS' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE billing_records ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCH_ITEMS' AND COLUMN_NAME = 'OBJECT_TYPE' AND NULLABLE = 'N';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batch_items MODIFY object_type NULL'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEHYDRATION_BATCH_ITEMS' AND COLUMN_NAME = 'OBJECT_ID' AND NULLABLE = 'N';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE dehydration_batch_items MODIFY object_id NULL'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CASE_MEDIA_ASSETS' AND COLUMN_NAME = 'CAPTURE_NODE' AND NULLABLE = 'N';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE case_media_assets MODIFY capture_node NULL'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'REAGENTS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE reagents (id VARCHAR2(64) NOT NULL, reagent_code VARCHAR2(64) NOT NULL, reagent_name VARCHAR2(100) NOT NULL, specification VARCHAR2(100), unit VARCHAR2(32), manufacturer VARCHAR2(200), default_low_stock_threshold NUMBER(18, 2), default_near_expiry_days NUMBER(10), enabled NUMBER(1) DEFAULT 1, remarks VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_reagents PRIMARY KEY (id), CONSTRAINT uk_reagents_code UNIQUE (reagent_code))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'REAGENT_STOCKS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE reagent_stocks (id VARCHAR2(64) NOT NULL, reagent_id VARCHAR2(64) NOT NULL, batch_no VARCHAR2(64) NOT NULL, stock_quantity NUMBER(18, 2) NOT NULL, stock_status VARCHAR2(32) NOT NULL, expiry_date DATE, storage_location VARCHAR2(200), low_stock_threshold NUMBER(18, 2), near_expiry_days NUMBER(10), remarks VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_reagent_stocks PRIMARY KEY (id), CONSTRAINT uk_reagent_stocks_batch UNIQUE (reagent_id, batch_no), CONSTRAINT fk_reagent_stocks_reagent FOREIGN KEY (reagent_id) REFERENCES reagents (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'EQUIPMENT_RECORDS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE equipment_records (id VARCHAR2(64) NOT NULL, equipment_code VARCHAR2(64) NOT NULL, equipment_name VARCHAR2(100) NOT NULL, equipment_category VARCHAR2(64), model_no VARCHAR2(100), equipment_status VARCHAR2(32) NOT NULL, location_description VARCHAR2(200), enabled_at TIMESTAMP, next_maintenance_at TIMESTAMP, remarks VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_equipment_records PRIMARY KEY (id), CONSTRAINT uk_equipment_records_code UNIQUE (equipment_code))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'EQUIPMENT_MAINTENANCE_LOGS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE equipment_maintenance_logs (id VARCHAR2(64) NOT NULL, equipment_id VARCHAR2(64) NOT NULL, maintenance_type VARCHAR2(32) NOT NULL, maintenance_status VARCHAR2(32) NOT NULL, performed_at TIMESTAMP NOT NULL, performed_by_user_id VARCHAR2(64), performed_by_name VARCHAR2(100), description VARCHAR2(1000), next_maintenance_at TIMESTAMP, remarks VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_equipment_maintenance_logs PRIMARY KEY (id), CONSTRAINT fk_equipment_maintenance_logs_equipment FOREIGN KEY (equipment_id) REFERENCES equipment_records (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'INTEGRATION_TASKS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE integration_tasks (id VARCHAR2(64) NOT NULL, task_type VARCHAR2(64) NOT NULL, business_type VARCHAR2(64) NOT NULL, business_id VARCHAR2(64) NOT NULL, stage_code VARCHAR2(64) NOT NULL, external_system VARCHAR2(64), request_payload CLOB, response_payload CLOB, task_status VARCHAR2(32) NOT NULL, retry_count NUMBER(10) DEFAULT 0 NOT NULL, max_retry_count NUMBER(10) DEFAULT 3 NOT NULL, next_retry_at TIMESTAMP, last_attempt_at TIMESTAMP, last_error_code VARCHAR2(64), last_error_message VARCHAR2(1000), compensation_status VARCHAR2(32) DEFAULT ''NONE'' NOT NULL, reconciliation_status VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL, resolved_at TIMESTAMP, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_integration_tasks PRIMARY KEY (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HISTORICAL_IMPORT_JOBS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE historical_import_jobs (id VARCHAR2(64) NOT NULL, source_system VARCHAR2(64) NOT NULL, patient_id VARCHAR2(64), pathology_no VARCHAR2(64), application_no VARCHAR2(64), import_status VARCHAR2(32) NOT NULL, requested_by_user_id VARCHAR2(64), requested_by_name VARCHAR2(100), total_count NUMBER(10) DEFAULT 0 NOT NULL, success_count NUMBER(10) DEFAULT 0 NOT NULL, failure_count NUMBER(10) DEFAULT 0 NOT NULL, requested_at TIMESTAMP NOT NULL, completed_at TIMESTAMP, last_error_message VARCHAR2(1000), remarks VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_historical_import_jobs PRIMARY KEY (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HISTORICAL_REPORTS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE historical_reports (id VARCHAR2(64) NOT NULL, import_job_id VARCHAR2(64), source_system VARCHAR2(64) NOT NULL, external_report_no VARCHAR2(64) NOT NULL, patient_id VARCHAR2(64), patient_name VARCHAR2(100), pathology_no VARCHAR2(64), application_no VARCHAR2(64), report_date TIMESTAMP, final_diagnosis VARCHAR2(1000), report_summary CLOB, raw_payload CLOB, source_department_name VARCHAR2(100), source_doctor_name VARCHAR2(100), attachment_url VARCHAR2(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_historical_reports PRIMARY KEY (id), CONSTRAINT uk_historical_reports_source_report UNIQUE (source_system, external_report_no), CONSTRAINT fk_historical_reports_job FOREIGN KEY (import_job_id) REFERENCES historical_import_jobs (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'HISTORICAL_REPORT_VERSIONS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE historical_report_versions (id VARCHAR2(64) NOT NULL, historical_report_id VARCHAR2(64) NOT NULL, version_no NUMBER(10) NOT NULL, final_diagnosis VARCHAR2(1000), report_summary CLOB, raw_payload CLOB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_historical_report_versions PRIMARY KEY (id), CONSTRAINT uk_historical_report_versions UNIQUE (historical_report_id, version_no), CONSTRAINT fk_historical_report_versions_report FOREIGN KEY (historical_report_id) REFERENCES historical_reports (id))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'STAT_INDICATOR_DEFINITIONS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE stat_indicator_definitions (id VARCHAR2(64) NOT NULL, indicator_code VARCHAR2(64) NOT NULL, indicator_name VARCHAR2(100) NOT NULL, indicator_category VARCHAR2(32) NOT NULL, metric_scope VARCHAR2(32), aggregation_type VARCHAR2(32), description VARCHAR2(500), sort_order NUMBER(10) DEFAULT 0 NOT NULL, enabled NUMBER(1) DEFAULT 1 NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_stat_indicator_definitions PRIMARY KEY (id), CONSTRAINT uk_stat_indicator_definitions_code UNIQUE (indicator_code))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'STAT_REPORT_TEMPLATES';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE stat_report_templates (id VARCHAR2(64) NOT NULL, template_code VARCHAR2(64) NOT NULL, template_name VARCHAR2(100) NOT NULL, template_type VARCHAR2(32) NOT NULL, indicator_code VARCHAR2(64), default_columns CLOB, parameter_schema CLOB, sort_order NUMBER(10) DEFAULT 0 NOT NULL, enabled NUMBER(1) DEFAULT 1 NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT pk_stat_report_templates PRIMARY KEY (id), CONSTRAINT uk_stat_report_templates_code UNIQUE (template_code))'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'STAT_EXPORT_JOBS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE stat_export_jobs (id VARCHAR2(64) NOT NULL, export_no VARCHAR2(64) NOT NULL, template_id VARCHAR2(64), indicator_code VARCHAR2(64), export_status VARCHAR2(32) NOT NULL, filter_payload CLOB, file_name VARCHAR2(255), content_type VARCHAR2(100), requested_by_user_id VARCHAR2(64), requested_by_name VARCHAR2(100), error_message VARCHAR2(1000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP, CONSTRAINT pk_stat_export_jobs PRIMARY KEY (id), CONSTRAINT uk_stat_export_jobs_export_no UNIQUE (export_no), CONSTRAINT fk_stat_export_jobs_template FOREIGN KEY (template_id) REFERENCES stat_report_templates (id))'; END IF;
END;
/

DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_TECH_SPEC_REG_STATUS_CREATED';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_tech_spec_reg_status_created ON technical_specimen_registrations (registration_status, created_at)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_TECH_SPEC_REG_APPLICATION';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_tech_spec_reg_application ON technical_specimen_registrations (application_id)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_INTEGRATION_TASKS_BUSINESS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_integration_tasks_business ON integration_tasks (business_type, business_id)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_INTEGRATION_TASKS_STATUS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_integration_tasks_status ON integration_tasks (task_status, next_retry_at)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BILLING_RECORDS_CASE_STAGE';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_billing_records_case_stage ON billing_records (case_id, billing_stage)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BILLING_RECORDS_STATUS_TIME';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_billing_records_status_time ON billing_records (billing_status, billed_at)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_HISTORICAL_IMPORT_JOBS_SOURCE_STATUS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_historical_import_jobs_source_status ON historical_import_jobs (source_system, import_status)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_HISTORICAL_REPORTS_PATIENT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_historical_reports_patient ON historical_reports (patient_id, report_date)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_HISTORICAL_REPORTS_PATHOLOGY';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_historical_reports_pathology ON historical_reports (pathology_no, report_date)'; END IF;
END;
/

DECLARE
    v_count INTEGER;
BEGIN
    UPDATE menus
    SET parent_id = 'MENU_M3_WORKFLOW',
        menu_code = 'M3_SPECIMEN_REGISTRATION',
        menu_name = '标本登记',
        menu_type = 'MENU',
        path = '/api/v1/technical-specimen-registrations/pending',
        component_name = 'TechnicalSpecimenRegistration',
        permission_prefix = 'm2:receipt',
        sort_order = 121,
        visible = 1,
        enabled = 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = 'MENU_M3_SPECIMEN_REGISTRATION';

    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO menus
            (id, parent_id, menu_code, menu_name, menu_type, path, component_name, permission_prefix,
             sort_order, visible, enabled, created_at, updated_at)
        VALUES
            ('MENU_M3_SPECIMEN_REGISTRATION', 'MENU_M3_WORKFLOW', 'M3_SPECIMEN_REGISTRATION', '标本登记',
             'MENU', '/api/v1/technical-specimen-registrations/pending', 'TechnicalSpecimenRegistration',
             'm2:receipt', 121, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM role_menus
    WHERE role_id = 'ROLE_PATHOLOGY_ADMIN'
      AND menu_id = 'MENU_M3_SPECIMEN_REGISTRATION';
    IF v_count = 0 THEN
        INSERT INTO role_menus (id, role_id, menu_id, assigned_at)
        VALUES ('RM_M3_SPEC_REG_ADMIN', 'ROLE_PATHOLOGY_ADMIN', 'MENU_M3_SPECIMEN_REGISTRATION', CURRENT_TIMESTAMP);
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM role_menus
    WHERE role_id = 'ROLE_M2_SPECIMEN_RECEIVE'
      AND menu_id = 'MENU_M3_SPECIMEN_REGISTRATION';
    IF v_count = 0 THEN
        INSERT INTO role_menus (id, role_id, menu_id, assigned_at)
        VALUES ('RM_M3_SPEC_REG_RECEIPT', 'ROLE_M2_SPECIMEN_RECEIVE', 'MENU_M3_SPECIMEN_REGISTRATION', CURRENT_TIMESTAMP);
    END IF;
END;
/
