INSERT INTO menus (id, parent_id, menu_code, menu_name, menu_type, path, component_name, permission_prefix, sort_order) VALUES
('MENU_M4_REVISION', 'MENU_M4_WORKFLOW', 'M4_REVISION', 'Report Revision', 'MENU', '/api/v1/report-revision-requests', 'ReportRevision', 'm4:revision', 135),
('MENU_M4_MEDICAL_ORDER', 'MENU_M4_WORKFLOW', 'M4_MEDICAL_ORDER', 'Medical Order', 'MENU', '/api/v1/medical-orders/pending', 'MedicalOrder', 'm4:order', 136),
('MENU_M4_CONSULTATION', 'MENU_M4_WORKFLOW', 'M4_CONSULTATION', 'Consultation', 'MENU', '/api/v1/consultations', 'Consultation', 'm4:consultation', 137);

INSERT INTO permissions (id, permission_code, permission_name, menu_id, action_key, http_method, resource_path, permission_group, sort_order) VALUES
('PERM_M4_REVISION_REQUEST_CREATE', 'PERM_M4_REVISION_REQUEST_CREATE', 'Revision request create', 'MENU_M4_REVISION', 'CREATE', 'POST', '/api/v1/report-revision-requests', 'M4', 142),
('PERM_M4_REVISION_APPROVE', 'PERM_M4_REVISION_APPROVE', 'Revision approve', 'MENU_M4_REVISION', 'APPROVE', 'POST', '/api/v1/report-revision-requests/{id}/approve', 'M4', 143),
('PERM_M4_MEDICAL_ORDER_CREATE', 'PERM_M4_MEDICAL_ORDER_CREATE', 'Medical order create', 'MENU_M4_MEDICAL_ORDER', 'CREATE', 'POST', '/api/v1/medical-orders', 'M4', 144),
('PERM_M4_MEDICAL_ORDER_CANCEL', 'PERM_M4_MEDICAL_ORDER_CANCEL', 'Medical order cancel', 'MENU_M4_MEDICAL_ORDER', 'CANCEL', 'POST', '/api/v1/medical-orders/{id}/cancel', 'M4', 145),
('PERM_M4_MEDICAL_ORDER_QUERY', 'PERM_M4_MEDICAL_ORDER_QUERY', 'Medical order query', 'MENU_M4_MEDICAL_ORDER', 'QUERY', 'GET', '/api/v1/medical-orders/pending', 'M4', 146),
('PERM_M4_MEDICAL_ORDER_ACCEPT', 'PERM_M4_MEDICAL_ORDER_ACCEPT', 'Medical order accept', 'MENU_M4_MEDICAL_ORDER', 'ACCEPT', 'POST', '/api/v1/medical-orders/{id}/accept', 'M4', 147),
('PERM_M4_MEDICAL_ORDER_COMPLETE', 'PERM_M4_MEDICAL_ORDER_COMPLETE', 'Medical order complete', 'MENU_M4_MEDICAL_ORDER', 'COMPLETE', 'POST', '/api/v1/medical-orders/{id}/complete', 'M4', 148),
('PERM_M4_CONSULTATION_CREATE', 'PERM_M4_CONSULTATION_CREATE', 'Consultation create', 'MENU_M4_CONSULTATION', 'CREATE', 'POST', '/api/v1/consultations', 'M4', 149),
('PERM_M4_CONSULTATION_COMMENT', 'PERM_M4_CONSULTATION_COMMENT', 'Consultation comment', 'MENU_M4_CONSULTATION', 'COMMENT', 'POST', '/api/v1/consultations/{id}/participants/{participantId}/comment', 'M4', 150),
('PERM_M4_CONSULTATION_COMPLETE', 'PERM_M4_CONSULTATION_COMPLETE', 'Consultation complete', 'MENU_M4_CONSULTATION', 'COMPLETE', 'POST', '/api/v1/consultations/{id}/complete', 'M4', 151);

INSERT INTO roles (id, role_code, role_name, role_type, data_scope, remarks) VALUES
('ROLE_M4_MEDICAL_ORDER_EXECUTE', 'M4_MEDICAL_ORDER_EXECUTE', 'M4 Medical Order Execute', 'BUSINESS', 'DEPARTMENT', 'M4 medical order execution workstation');

INSERT INTO role_permissions (id, role_id, permission_id, assigned_at) VALUES
('RP_M4_ADMIN_REVISION_CREATE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_REVISION_REQUEST_CREATE', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_REVISION_APPROVE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_REVISION_APPROVE', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_ORDER_CREATE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_MEDICAL_ORDER_CREATE', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_ORDER_CANCEL', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_MEDICAL_ORDER_CANCEL', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_ORDER_QUERY', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_MEDICAL_ORDER_QUERY', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_ORDER_ACCEPT', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_MEDICAL_ORDER_ACCEPT', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_ORDER_COMPLETE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_MEDICAL_ORDER_COMPLETE', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_CONSULT_CREATE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_CONSULTATION_CREATE', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_CONSULT_COMMENT', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_CONSULTATION_COMMENT', CURRENT_TIMESTAMP),
('RP_M4_ADMIN_CONSULT_COMPLETE', 'ROLE_PATHOLOGY_ADMIN', 'PERM_M4_CONSULTATION_COMPLETE', CURRENT_TIMESTAMP),
('RP_M4_DIAG_REVISION_CREATE', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_REVISION_REQUEST_CREATE', CURRENT_TIMESTAMP),
('RP_M4_DIAG_ORDER_CREATE', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_MEDICAL_ORDER_CREATE', CURRENT_TIMESTAMP),
('RP_M4_DIAG_ORDER_CANCEL', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_MEDICAL_ORDER_CANCEL', CURRENT_TIMESTAMP),
('RP_M4_DIAG_CONSULT_CREATE', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_CONSULTATION_CREATE', CURRENT_TIMESTAMP),
('RP_M4_DIAG_CONSULT_COMMENT', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_CONSULTATION_COMMENT', CURRENT_TIMESTAMP),
('RP_M4_DIAG_CONSULT_COMPLETE', 'ROLE_M4_DIAGNOSIS', 'PERM_M4_CONSULTATION_COMPLETE', CURRENT_TIMESTAMP),
('RP_M4_REVIEW_CONSULT_COMMENT', 'ROLE_M4_REVIEW', 'PERM_M4_CONSULTATION_COMMENT', CURRENT_TIMESTAMP),
('RP_M4_SIGN_REVISION_APPROVE', 'ROLE_M4_SIGN', 'PERM_M4_REVISION_APPROVE', CURRENT_TIMESTAMP),
('RP_M4_SIGN_CONSULT_COMMENT', 'ROLE_M4_SIGN', 'PERM_M4_CONSULTATION_COMMENT', CURRENT_TIMESTAMP),
('RP_M4_ORDER_EXEC_QUERY', 'ROLE_M4_MEDICAL_ORDER_EXECUTE', 'PERM_M4_MEDICAL_ORDER_QUERY', CURRENT_TIMESTAMP),
('RP_M4_ORDER_EXEC_ACCEPT', 'ROLE_M4_MEDICAL_ORDER_EXECUTE', 'PERM_M4_MEDICAL_ORDER_ACCEPT', CURRENT_TIMESTAMP),
('RP_M4_ORDER_EXEC_COMPLETE', 'ROLE_M4_MEDICAL_ORDER_EXECUTE', 'PERM_M4_MEDICAL_ORDER_COMPLETE', CURRENT_TIMESTAMP);

INSERT INTO users (id, user_code, login_name, name, role, enabled, created_at, updated_at) VALUES
('USER_M4_ORDER_EXECUTE', 'U-M4-ORDER-EXEC', 'm4.order.execute', 'M4 Order Execute', 'M4_MEDICAL_ORDER_EXECUTE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (id, user_id, role_id, is_primary, assigned_at, assigned_by_name) VALUES
('UR_M4_ORDER_EXECUTE', 'USER_M4_ORDER_EXECUTE', 'ROLE_M4_MEDICAL_ORDER_EXECUTE', 1, CURRENT_TIMESTAMP, 'system');
