CREATE TABLE application_registration_workbench (
    application_id VARCHAR(64) NOT NULL,
    inpatient_no VARCHAR(64),
    bed_no VARCHAR(64),
    ward_name VARCHAR(100),
    phone VARCHAR(32),
    id_no VARCHAR(64),
    check_item VARCHAR(200),
    clinical_history VARCHAR(1000),
    imaging_result VARCHAR(1000),
    endoscopy_diagnosis VARCHAR(1000),
    delivery_requirement VARCHAR(200),
    specimen_type VARCHAR(100),
    surgery_name VARCHAR(200),
    clinical_findings VARCHAR(1000),
    fixative_type VARCHAR(100),
    fixation_person VARCHAR(100),
    fixation_time TIMESTAMP,
    building_id VARCHAR(64),
    room_id VARCHAR(64),
    contagious_isolation INTEGER DEFAULT 0,
    contagious_hiv INTEGER DEFAULT 0,
    contagious_tuberculosis INTEGER DEFAULT 0,
    contagious_hepatitis INTEGER DEFAULT 0,
    contagious_syphilis INTEGER DEFAULT 0,
    gynecology_menopause INTEGER DEFAULT 0,
    last_menstrual_period VARCHAR(64),
    hpv_result VARCHAR(100),
    previous_cytology VARCHAR(1000),
    previous_treatment VARCHAR(1000),
    additional_notes VARCHAR(1000),
    condition_abnormal_bleeding INTEGER DEFAULT 0,
    condition_birth_control INTEGER DEFAULT 0,
    condition_hormone_replacement INTEGER DEFAULT 0,
    condition_hysterectomy INTEGER DEFAULT 0,
    condition_iud INTEGER DEFAULT 0,
    condition_lactation INTEGER DEFAULT 0,
    condition_pregnancy INTEGER DEFAULT 0,
    condition_radiotherapy INTEGER DEFAULT 0,
    other_special_condition VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_application_registration_workbench PRIMARY KEY (application_id),
    CONSTRAINT fk_application_registration_workbench_application FOREIGN KEY (application_id) REFERENCES applications (id)
);

CREATE INDEX idx_app_reg_workbench_inpatient_no
    ON application_registration_workbench (inpatient_no);
