INSERT INTO users (id, user_code, login_name, name, role, enabled, created_at, updated_at) VALUES
('USER_M1_ADMIN', 'U-M1-ADMIN', 'm1.admin', 'M1 Admin', 'PATHOLOGY_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_DOCTOR', 'U-M1-DOCTOR', 'm1.doctor', 'M1 Doctor', 'PATHOLOGY_DOCTOR', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_TECHNICIAN', 'U-M1-TECH', 'm1.technician', 'M1 Technician', 'PATHOLOGY_TECHNICIAN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_ARCHIVE', 'U-M1-ARCHIVE', 'm1.archive', 'M1 Archive', 'ARCHIVE_MANAGER', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_REAGENT', 'U-M1-REAGENT', 'm1.reagent', 'M1 Reagent', 'REAGENT_DEVICE_MANAGER', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_QUALITY', 'U-M1-QUALITY', 'm1.quality', 'M1 Quality', 'QUALITY_MANAGER', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_M1_NO_PERMISSION', 'U-M1-NOAUTH', 'm1.noauth', 'M1 No Permission', NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (id, user_id, role_id, is_primary, assigned_at, assigned_by_name) VALUES
('UR_M1_ADMIN', 'USER_M1_ADMIN', 'ROLE_PATHOLOGY_ADMIN', 1, CURRENT_TIMESTAMP, 'system'),
('UR_M1_DOCTOR', 'USER_M1_DOCTOR', 'ROLE_PATHOLOGY_DOCTOR', 1, CURRENT_TIMESTAMP, 'system'),
('UR_M1_TECHNICIAN', 'USER_M1_TECHNICIAN', 'ROLE_PATHOLOGY_TECHNICIAN', 1, CURRENT_TIMESTAMP, 'system'),
('UR_M1_ARCHIVE', 'USER_M1_ARCHIVE', 'ROLE_ARCHIVE_MANAGER', 1, CURRENT_TIMESTAMP, 'system'),
('UR_M1_REAGENT', 'USER_M1_REAGENT', 'ROLE_REAGENT_DEVICE_MANAGER', 1, CURRENT_TIMESTAMP, 'system'),
('UR_M1_QUALITY', 'USER_M1_QUALITY', 'ROLE_QUALITY_MANAGER', 1, CURRENT_TIMESTAMP, 'system');
