UPDATE roles
SET role_name = CASE id
    WHEN 'ROLE_M2_CLINICAL_REGISTER' THEN 'M2 临床登记员'
    WHEN 'ROLE_M2_FIXATION_VERIFY' THEN 'M2 固定核对员'
    WHEN 'ROLE_M2_TRANSPORT_HANDOVER' THEN 'M2 转运交接员'
    WHEN 'ROLE_M2_SPECIMEN_RECEIVE' THEN 'M2 标本接收员'
    WHEN 'ROLE_M2_TRACKING_QUERY' THEN 'M2 追踪查询员'
    WHEN 'ROLE_M2_CLINICAL_IMPORT' THEN 'M2 临床导入员'
    WHEN 'ROLE_M3_GROSSING' THEN 'M3 取材描写员'
    WHEN 'ROLE_M3_DEHYDRATION' THEN 'M3 脱水员'
    WHEN 'ROLE_M3_EMBEDDING' THEN 'M3 包埋员'
    WHEN 'ROLE_M3_SLICING' THEN 'M3 切片员'
    WHEN 'ROLE_M3_STAINING' THEN 'M3 染色员'
    WHEN 'ROLE_M3_REWORK' THEN 'M3 返工处理员'
    WHEN 'ROLE_M3_TRACKING' THEN 'M3 技术追踪员'
    WHEN 'ROLE_M4_ASSIGN' THEN 'M4 诊断分配员'
    WHEN 'ROLE_M4_DIAGNOSIS' THEN 'M4 诊断医生'
    WHEN 'ROLE_M4_REVIEW' THEN 'M4 审核医生'
    WHEN 'ROLE_M4_SIGN' THEN 'M4 签发医生'
    WHEN 'ROLE_M4_TRACKING' THEN 'M4 报告追踪员'
    WHEN 'ROLE_M4_MEDICAL_ORDER_EXECUTE' THEN 'M4 医嘱执行员'
    ELSE role_name
  END,
  remarks = CASE id
    WHEN 'ROLE_M2_CLINICAL_REGISTER' THEN 'M2 临床登记工作站'
    WHEN 'ROLE_M2_FIXATION_VERIFY' THEN 'M2 固定核对工作站'
    WHEN 'ROLE_M2_TRANSPORT_HANDOVER' THEN 'M2 转运交接工作站'
    WHEN 'ROLE_M2_SPECIMEN_RECEIVE' THEN 'M2 标本接收工作站'
    WHEN 'ROLE_M2_TRACKING_QUERY' THEN 'M2 追踪查询工作站'
    WHEN 'ROLE_M2_CLINICAL_IMPORT' THEN 'M2 临床导入工作站'
    WHEN 'ROLE_M3_GROSSING' THEN 'M3 取材描写工作站'
    WHEN 'ROLE_M3_DEHYDRATION' THEN 'M3 脱水工作站'
    WHEN 'ROLE_M3_EMBEDDING' THEN 'M3 包埋工作站'
    WHEN 'ROLE_M3_SLICING' THEN 'M3 切片工作站'
    WHEN 'ROLE_M3_STAINING' THEN 'M3 染色工作站'
    WHEN 'ROLE_M3_REWORK' THEN 'M3 返工工作站'
    WHEN 'ROLE_M3_TRACKING' THEN 'M3 技术追踪工作站'
    WHEN 'ROLE_M4_ASSIGN' THEN 'M4 诊断分配工作站'
    WHEN 'ROLE_M4_DIAGNOSIS' THEN 'M4 诊断工作站'
    WHEN 'ROLE_M4_REVIEW' THEN 'M4 审核工作站'
    WHEN 'ROLE_M4_SIGN' THEN 'M4 签发工作站'
    WHEN 'ROLE_M4_TRACKING' THEN 'M4 报告追踪工作站'
    WHEN 'ROLE_M4_MEDICAL_ORDER_EXECUTE' THEN 'M4 病理医嘱执行工作站'
    ELSE remarks
  END
WHERE id IN (
  'ROLE_M2_CLINICAL_REGISTER',
  'ROLE_M2_FIXATION_VERIFY',
  'ROLE_M2_TRANSPORT_HANDOVER',
  'ROLE_M2_SPECIMEN_RECEIVE',
  'ROLE_M2_TRACKING_QUERY',
  'ROLE_M2_CLINICAL_IMPORT',
  'ROLE_M3_GROSSING',
  'ROLE_M3_DEHYDRATION',
  'ROLE_M3_EMBEDDING',
  'ROLE_M3_SLICING',
  'ROLE_M3_STAINING',
  'ROLE_M3_REWORK',
  'ROLE_M3_TRACKING',
  'ROLE_M4_ASSIGN',
  'ROLE_M4_DIAGNOSIS',
  'ROLE_M4_REVIEW',
  'ROLE_M4_SIGN',
  'ROLE_M4_TRACKING',
  'ROLE_M4_MEDICAL_ORDER_EXECUTE'
);

UPDATE menus
SET menu_name = CASE id
    WHEN 'MENU_M2_WORKFLOW' THEN '临床送检'
    WHEN 'MENU_M2_CLINICAL' THEN '申请与登记'
    WHEN 'MENU_M2_FIXATION' THEN '固定核对'
    WHEN 'MENU_M2_TRANSPORT' THEN '转运交接'
    WHEN 'MENU_M2_RECEIPT' THEN '标本接收工作台'
    WHEN 'MENU_M2_TRACKING' THEN '追踪与异常'
    WHEN 'MENU_M3_WORKFLOW' THEN '制片管理'
    WHEN 'MENU_M3_GROSSING' THEN '取材描写工作站'
    WHEN 'MENU_M3_DEHYDRATION' THEN '脱水工作站'
    WHEN 'MENU_M3_EMBEDDING' THEN '包埋工作站'
    WHEN 'MENU_M3_SLICING' THEN '切片工作站'
    WHEN 'MENU_M3_STAINING' THEN '染色出片工作站'
    WHEN 'MENU_M3_REWORK' THEN '返工工作站'
    WHEN 'MENU_M3_TRACKING' THEN '技术追踪'
    WHEN 'MENU_M3_TASKS' THEN '任务池'
    WHEN 'MENU_M4_WORKFLOW' THEN '诊断管理'
    WHEN 'MENU_M4_ASSIGN' THEN '诊断分配'
    WHEN 'MENU_M4_WORKBENCH' THEN '诊断平台工作站'
    WHEN 'MENU_M4_REPORT' THEN '病理报告'
    WHEN 'MENU_M4_TRACKING' THEN '报告追踪'
    WHEN 'MENU_M4_REVISION' THEN '报告修订'
    WHEN 'MENU_M4_MEDICAL_ORDER' THEN '病理医嘱执行'
    WHEN 'MENU_M4_CONSULTATION' THEN '会诊管理'
    WHEN 'MENU_M5_SUPPORT' THEN '归档与设备试剂管理'
    WHEN 'MENU_M5_ARCHIVE' THEN '归档管理'
    WHEN 'MENU_M5_REAGENT' THEN '试剂耗材管理'
    WHEN 'MENU_M5_EQUIPMENT' THEN '仪器设备管理'
    WHEN 'MENU_M6_SUPPORT' THEN '数据统计与分析'
    WHEN 'MENU_M6_INTEGRATION' THEN '集成任务管理'
    WHEN 'MENU_M6_BILLING' THEN '收费管理'
    WHEN 'MENU_M6_HISTORY' THEN '历史报告'
    WHEN 'MENU_M6_STAT' THEN '自定义统计分析'
    ELSE menu_name
  END
WHERE id IN (
  'MENU_M2_WORKFLOW',
  'MENU_M2_CLINICAL',
  'MENU_M2_FIXATION',
  'MENU_M2_TRANSPORT',
  'MENU_M2_RECEIPT',
  'MENU_M2_TRACKING',
  'MENU_M3_WORKFLOW',
  'MENU_M3_GROSSING',
  'MENU_M3_DEHYDRATION',
  'MENU_M3_EMBEDDING',
  'MENU_M3_SLICING',
  'MENU_M3_STAINING',
  'MENU_M3_REWORK',
  'MENU_M3_TRACKING',
  'MENU_M3_TASKS',
  'MENU_M4_WORKFLOW',
  'MENU_M4_ASSIGN',
  'MENU_M4_WORKBENCH',
  'MENU_M4_REPORT',
  'MENU_M4_TRACKING',
  'MENU_M4_REVISION',
  'MENU_M4_MEDICAL_ORDER',
  'MENU_M4_CONSULTATION',
  'MENU_M5_SUPPORT',
  'MENU_M5_ARCHIVE',
  'MENU_M5_REAGENT',
  'MENU_M5_EQUIPMENT',
  'MENU_M6_SUPPORT',
  'MENU_M6_INTEGRATION',
  'MENU_M6_BILLING',
  'MENU_M6_HISTORY',
  'MENU_M6_STAT'
);

UPDATE permissions
SET permission_name = CASE id
    WHEN 'PERM_SYS_USER_QUERY' THEN '查询系统用户'
    WHEN 'PERM_SYS_USER_CREATE' THEN '创建系统用户'
    WHEN 'PERM_SYS_USER_UPDATE' THEN '更新系统用户'
    WHEN 'PERM_SPECIMEN_REGISTER' THEN '标本登记'
    WHEN 'PERM_FIXATION_VERIFY' THEN '固定核对'
    WHEN 'PERM_TRANSPORT_HANDOVER' THEN '转运交接'
    WHEN 'PERM_SPECIMEN_RECEIVE' THEN '标本接收'
    WHEN 'PERM_SPECIMEN_TRACKING_QUERY' THEN '追踪查询'
    WHEN 'PERM_CLINICAL_IMPORT' THEN '临床导入'
    WHEN 'PERM_M3_GROSSING' THEN '取材描写操作'
    WHEN 'PERM_M3_DEHYDRATION' THEN '脱水操作'
    WHEN 'PERM_M3_EMBEDDING' THEN '包埋操作'
    WHEN 'PERM_M3_SLICING' THEN '切片操作'
    WHEN 'PERM_M3_STAINING' THEN '染色操作'
    WHEN 'PERM_M3_REWORK' THEN '返工操作'
    WHEN 'PERM_M3_TECH_TRACKING_QUERY' THEN '技术追踪查询'
    WHEN 'PERM_M3_TECH_TASK_QUERY' THEN '技术任务查询'
    WHEN 'PERM_M4_DIAG_TASK_QUERY' THEN '诊断任务查询'
    WHEN 'PERM_M4_ASSIGN' THEN '诊断分配'
    WHEN 'PERM_M4_ACCEPT' THEN '诊断接收'
    WHEN 'PERM_M4_START' THEN '开始诊断'
    WHEN 'PERM_M4_WORKBENCH_QUERY' THEN '诊断工作台查询'
    WHEN 'PERM_M4_REPORT_CREATE' THEN '创建病理报告'
    WHEN 'PERM_M4_REPORT_SUBMIT' THEN '提交病理报告'
    WHEN 'PERM_M4_REPORT_REVIEW' THEN '审核病理报告'
    WHEN 'PERM_M4_REPORT_SIGN' THEN '签发病理报告'
    WHEN 'PERM_M4_REPORT_PUBLISH' THEN '发布病理报告'
    WHEN 'PERM_M4_REPORT_TRACKING_QUERY' THEN '报告追踪查询'
    WHEN 'PERM_M4_REVISION_REQUEST_CREATE' THEN '创建报告修订'
    WHEN 'PERM_M4_REVISION_APPROVE' THEN '审批报告修订'
    WHEN 'PERM_M4_MEDICAL_ORDER_CREATE' THEN '创建病理医嘱'
    WHEN 'PERM_M4_MEDICAL_ORDER_CANCEL' THEN '取消病理医嘱'
    WHEN 'PERM_M4_MEDICAL_ORDER_QUERY' THEN '查询病理医嘱'
    WHEN 'PERM_M4_MEDICAL_ORDER_ACCEPT' THEN '接收病理医嘱'
    WHEN 'PERM_M4_MEDICAL_ORDER_COMPLETE' THEN '完成病理医嘱'
    WHEN 'PERM_M4_CONSULTATION_CREATE' THEN '创建会诊'
    WHEN 'PERM_M4_CONSULTATION_COMMENT' THEN '填写会诊意见'
    WHEN 'PERM_M4_CONSULTATION_COMPLETE' THEN '完成会诊'
    WHEN 'PERM_M5_ARCHIVE_CABINET_QUERY' THEN '查询档案柜'
    WHEN 'PERM_M5_ARCHIVE_CABINET_CREATE' THEN '创建档案柜'
    WHEN 'PERM_M5_ARCHIVE_CABINET_UPDATE' THEN '更新档案柜'
    WHEN 'PERM_M5_APPLICATION_FORM_ARCHIVE' THEN '申请单归档'
    WHEN 'PERM_M5_EMBEDDING_BOX_ARCHIVE' THEN '蜡块归档'
    WHEN 'PERM_M5_SLIDE_ARCHIVE' THEN '玻片归档'
    WHEN 'PERM_M5_ARCHIVE_QUERY' THEN '查询归档记录'
    WHEN 'PERM_M5_LOAN_CREATE' THEN '创建借阅'
    WHEN 'PERM_M5_LOAN_RETURN' THEN '归还借阅'
    WHEN 'PERM_M5_LOAN_QUERY' THEN '查询借阅'
    WHEN 'PERM_M5_REAGENT_QUERY' THEN '查询试剂耗材'
    WHEN 'PERM_M5_REAGENT_CREATE' THEN '创建试剂耗材'
    WHEN 'PERM_M5_REAGENT_UPDATE' THEN '更新试剂耗材'
    WHEN 'PERM_M5_REAGENT_STOCK_QUERY' THEN '查询试剂库存'
    WHEN 'PERM_M5_REAGENT_STOCK_UPDATE' THEN '更新试剂库存'
    WHEN 'PERM_M5_REAGENT_WARNING_QUERY' THEN '查询试剂预警'
    WHEN 'PERM_M5_EQUIPMENT_QUERY' THEN '查询仪器设备'
    WHEN 'PERM_M5_EQUIPMENT_CREATE' THEN '创建仪器设备'
    WHEN 'PERM_M5_EQUIPMENT_UPDATE' THEN '更新仪器设备'
    WHEN 'PERM_M5_EQUIPMENT_MAINTENANCE_CREATE' THEN '创建设备维护记录'
    WHEN 'PERM_M5_EQUIPMENT_WARNING_QUERY' THEN '查询设备预警'
    WHEN 'PERM_M6_INTEGRATION_TASK_QUERY' THEN '查询集成任务'
    WHEN 'PERM_M6_BILLING_QUERY' THEN '查询收费记录'
    WHEN 'PERM_M6_BILLING_RECEIPT' THEN '收费回执'
    WHEN 'PERM_M6_BILLING_RETRY' THEN '收费重试'
    WHEN 'PERM_M6_BILLING_RECONCILE' THEN '收费对账'
    WHEN 'PERM_M6_HISTORY_IMPORT' THEN '导入历史报告'
    WHEN 'PERM_M6_HISTORY_QUERY' THEN '查询历史报告'
    WHEN 'PERM_M6_STAT_INDICATOR_QUERY' THEN '查询统计指标'
    WHEN 'PERM_M6_STAT_TEMPLATE_QUERY' THEN '查询统计模板'
    WHEN 'PERM_M6_STAT_REPORT_QUERY' THEN '查询统计报表'
    WHEN 'PERM_M6_STAT_REPORT_EXPORT' THEN '导出统计报表'
    ELSE permission_name
  END
WHERE id IN (
  'PERM_SYS_USER_QUERY',
  'PERM_SYS_USER_CREATE',
  'PERM_SYS_USER_UPDATE',
  'PERM_SPECIMEN_REGISTER',
  'PERM_FIXATION_VERIFY',
  'PERM_TRANSPORT_HANDOVER',
  'PERM_SPECIMEN_RECEIVE',
  'PERM_SPECIMEN_TRACKING_QUERY',
  'PERM_CLINICAL_IMPORT',
  'PERM_M3_GROSSING',
  'PERM_M3_DEHYDRATION',
  'PERM_M3_EMBEDDING',
  'PERM_M3_SLICING',
  'PERM_M3_STAINING',
  'PERM_M3_REWORK',
  'PERM_M3_TECH_TRACKING_QUERY',
  'PERM_M3_TECH_TASK_QUERY',
  'PERM_M4_DIAG_TASK_QUERY',
  'PERM_M4_ASSIGN',
  'PERM_M4_ACCEPT',
  'PERM_M4_START',
  'PERM_M4_WORKBENCH_QUERY',
  'PERM_M4_REPORT_CREATE',
  'PERM_M4_REPORT_SUBMIT',
  'PERM_M4_REPORT_REVIEW',
  'PERM_M4_REPORT_SIGN',
  'PERM_M4_REPORT_PUBLISH',
  'PERM_M4_REPORT_TRACKING_QUERY',
  'PERM_M4_REVISION_REQUEST_CREATE',
  'PERM_M4_REVISION_APPROVE',
  'PERM_M4_MEDICAL_ORDER_CREATE',
  'PERM_M4_MEDICAL_ORDER_CANCEL',
  'PERM_M4_MEDICAL_ORDER_QUERY',
  'PERM_M4_MEDICAL_ORDER_ACCEPT',
  'PERM_M4_MEDICAL_ORDER_COMPLETE',
  'PERM_M4_CONSULTATION_CREATE',
  'PERM_M4_CONSULTATION_COMMENT',
  'PERM_M4_CONSULTATION_COMPLETE',
  'PERM_M5_ARCHIVE_CABINET_QUERY',
  'PERM_M5_ARCHIVE_CABINET_CREATE',
  'PERM_M5_ARCHIVE_CABINET_UPDATE',
  'PERM_M5_APPLICATION_FORM_ARCHIVE',
  'PERM_M5_EMBEDDING_BOX_ARCHIVE',
  'PERM_M5_SLIDE_ARCHIVE',
  'PERM_M5_ARCHIVE_QUERY',
  'PERM_M5_LOAN_CREATE',
  'PERM_M5_LOAN_RETURN',
  'PERM_M5_LOAN_QUERY',
  'PERM_M5_REAGENT_QUERY',
  'PERM_M5_REAGENT_CREATE',
  'PERM_M5_REAGENT_UPDATE',
  'PERM_M5_REAGENT_STOCK_QUERY',
  'PERM_M5_REAGENT_STOCK_UPDATE',
  'PERM_M5_REAGENT_WARNING_QUERY',
  'PERM_M5_EQUIPMENT_QUERY',
  'PERM_M5_EQUIPMENT_CREATE',
  'PERM_M5_EQUIPMENT_UPDATE',
  'PERM_M5_EQUIPMENT_MAINTENANCE_CREATE',
  'PERM_M5_EQUIPMENT_WARNING_QUERY',
  'PERM_M6_INTEGRATION_TASK_QUERY',
  'PERM_M6_BILLING_QUERY',
  'PERM_M6_BILLING_RECEIPT',
  'PERM_M6_BILLING_RETRY',
  'PERM_M6_BILLING_RECONCILE',
  'PERM_M6_HISTORY_IMPORT',
  'PERM_M6_HISTORY_QUERY',
  'PERM_M6_STAT_INDICATOR_QUERY',
  'PERM_M6_STAT_TEMPLATE_QUERY',
  'PERM_M6_STAT_REPORT_QUERY',
  'PERM_M6_STAT_REPORT_EXPORT'
);
