CREATE TABLE equipment_usage_records (
    id VARCHAR(64) NOT NULL,
    equipment_id VARCHAR(64),
    equipment_category_snapshot VARCHAR(64) NOT NULL,
    equipment_name_snapshot VARCHAR(100) NOT NULL,
    commonly_used INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    runtime_hours DECIMAL(8, 2) NOT NULL,
    diagnosis_count INTEGER NOT NULL DEFAULT 0,
    equipment_condition VARCHAR(32) NOT NULL,
    operator_user_id VARCHAR(64),
    operator_name VARCHAR(100) NOT NULL,
    usage_content VARCHAR(500),
    remarks VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_equipment_usage_records PRIMARY KEY (id),
    CONSTRAINT fk_equipment_usage_records_equipment FOREIGN KEY (equipment_id) REFERENCES equipment_records (id)
);
