#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
BACKEND_LOG_FILE="${BACKEND_LOG_FILE:-$ROOT_DIR/.logs/backend.log}"

if [ -z "${JAVA_HOME:-}" ]; then
  mkdir -p "$(dirname "$BACKEND_LOG_FILE")"
  echo "JAVA_HOME is not set. Please point it to JDK 17." | tee -a "$BACKEND_LOG_FILE" >&2
  exit 1
fi

export AUTH_CENTER_DATASOURCE_DRIVER_CLASS_NAME="${AUTH_CENTER_DATASOURCE_DRIVER_CLASS_NAME:-dm.jdbc.driver.DmDriver}"
export AUTH_CENTER_DATASOURCE_URL="${AUTH_CENTER_DATASOURCE_URL:-jdbc:dm://127.0.0.1:5236}"
export AUTH_CENTER_DATASOURCE_USERNAME="${AUTH_CENTER_DATASOURCE_USERNAME:-SYSDBA}"
export AUTH_CENTER_DATASOURCE_PASSWORD="${AUTH_CENTER_DATASOURCE_PASSWORD:-Dm.2027.Pwd.}"
export SECURITY_AUTH_JWT_SM2_PRIVATE_KEY="${SECURITY_AUTH_JWT_SM2_PRIVATE_KEY:-MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgFRpOClbX4u9Hpc+YDvXV7ShD1lfZk4EH0oyGF59PXQGgCgYIKoEcz1UBgi2hRANCAARrIcTZ4A4T3M55LVirPjtxhusNEndt2SmwXo5DfmQ+MHysYOCcFIOqI7YXUlrJ/e3D6owhe9Fo4nF7oZFzafRg}"
export SECURITY_AUTH_JWT_SM2_PUBLIC_KEY="${SECURITY_AUTH_JWT_SM2_PUBLIC_KEY:-MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEayHE2eAOE9zOeS1Yqz47cYbrDRJ3bdkpsF6OQ35kPjB8rGDgnBSDqiO2F1Jayf3tw+qMIXvRaOJxe6GRc2n0YA==}"

"$ROOT_DIR/scripts/dev/run-dev-service.sh" "auth-center" "$BACKEND_LOG_FILE"
